FROM nginx:1.27-alpine

LABEL org.opencontainers.image.title="Arul Docker Portfolio"
LABEL org.opencontainers.image.description="Basic custom Nginx image created for Docker practice"
LABEL org.opencontainers.image.authors="Arul Kumar"
LABEL org.opencontainers.image.version="1.0.0"

COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80
